version: 2.1

orbs:
  win: circleci/windows@1.1

jobs:
  build:
    executor:
      name: win/default
      tag: "10.4"
    steps:
      - checkout
      # - node/with-cache:
      - run: npm install
      - run: npm run test
