orbs: # declare what orbs we are going to use
  node: circleci/node@2.0.2 # the node orb provides common node-related configuration

version: 2.1 # using 2.1 provides access to orbs and other features

jobs:
  build:
    executor:
      name: win/default
      size: "medium"
    
    steps:
      - checkout
      - run: Write-Host "hello, Windows"
      - run: npm insall
      - run: npm run test

